version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnapp
    networks:
      - app-network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./uploads:/var/www/html/files
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge